### ISSUE TITLE
ModuleNotFoundError: No module named 'i2c_dev'

### ISSUE THREAD

**Issue by AlcalaRegenera** [the-raspberry-pi-guy/lcd#21]
Hello, I used your code last year with Python2, now i wrote a new program in Python3 and i got this error, I have searched in the network but i don't found any result to fix this problem, sorry If i made any mistake writing in this part, i recently entered in github

I followed all your steeps from your youtube video.

Traceback (most recent call last):
  File "demo_clock.py", line 8, in <module>
    import drivers
  File "/home/pi/lcd/drivers/__init__.py", line 1, in <module>
    from i2c_dev import Lcd
ModuleNotFoundError: No module named 'i2c_dev'

Thanks!

**Comment by cgomesu** [comment]
Just saw your message as I'm working on a script right now as well.  The error is a relative vs, absolute path issue related to py3.  In `drivers/__init__.py`, just change `i2c_dev` for `.i2c_dev` and you should be good to go.  (I think we can add such a change  to the repo as well because it won't affect Python2 execution. I'll send a PR tomorrow if no one is able to do so before then.)  Also, remember that you'll need to install `python3-smbus` if running Python 3.  Otherwise, you'll see a message complaining about the missing `smbus` pkg.  The install script only installs `smbus` for py2.

**Comment by AlcalaRegenera** [comment]
hello, I followed your steeps, it is working now, i am very happy and i really thanks you :) 

good work :)

Solved.

**Comment by piderking** [comment]
I was having a little trouble with this at first, but It works now. Thanks, good work.
