### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by jdarias** [the-raspberry-pi-guy/lcd#31]
I cloned the repo in my pi command line and created a script that I would like to publish. However I cannot push my commits, It asked me to create a personal access token to use instead of my password.  I did that but it denies me access anyway.

**Comment by the-raspberry-pi-guy** [comment]
Hi! Thank you for offering to contribute to the repo. In order to do this you will need to make a Pull Request. There's more information about how to do this on GitHub here: https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
