### ISSUE TITLE
addr i2c detection, re.findall function TypeError. [pull request... *sort of]

### ISSUE THREAD

**Issue by Kyuchumimo** [the-raspberry-pi-guy/lcd#33]
TypeError: cannot use a string pattern on a bytes-like object.
drivers/i2c_dev.py
```
62 ... try:
63 ...     self.addr = int('0x{}'.format(
64 ...                       findall("[0-9a-z]{2}(?!:)", check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER)]))[0]), base=16) \
65 ...                       if exists('/usr/sbin/i2cdetect') else addr_default
```
This should fix the problem:
```
62 ... try:
63 ...     self.addr = int('0x{}'.format(
64 ...                       findall("[0-9a-z]{2}(?!:)", check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER), encoding='utf8']))[0]), base=16) \
65 ...                       if exists('/usr/sbin/i2cdetect') else addr_default
```

**Comment by the-raspberry-pi-guy** [comment]
Are we still considering this a bug if this is a Python 3 compatibility issue @cgomesu ? Best to close this issue, or should we leave it open to clearly sign post?

**Comment by Kyuchumimo** [comment]
It has more to do with compatibility than a bug

**Comment by Kyuchumimo** [comment]
Done, this should fix the problem.
Works in both Python 2.7 and Python 3.7.3:
```
if bytes is not str:
    addr = int('0x{}'.format(
           findall("[0-9a-z]{2}(?!:)", check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER)], encoding='utf8'))[0]), base=16)
else:
    addr = int('0x{}'.format(
           findall("[0-9a-z]{2}(?!:)", check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER)]))[0]), base=16)
```

**Comment by cgomesu** [comment]
> Are we still considering this a bug if this is a Python 3 compatibility issue @cgomesu ?

> It has more to do with compatibility than a bug

I agree with you both.  I added the bug label for quick reference because we do not have custom labels in this repo.  I'll take care of that.

> Best to close this issue, or should we leave it open to clearly sign post?

Let's wait for a fix from @Kyuchumimo.  (See below.)

>Done, this should fix the problem.
>Works in both Python 2.7 and Python 3.7.3:
>```
>addr = int('0x{}'.format(
>       findall("[0-9a-z]{2}(?!:)", check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER)]).decode())[0]), base=16)
>```

Thanks, @Kyuchumimo.  I'll test the implementation when I get back home tomorrow.  In the meantime, could you please submit a PR including only this change and linking to this issue?

**Comment by cgomesu** [comment]
>```
>check_output(['/usr/sbin/i2cdetect', '-y', str(BUS_NUMBER)]).decode())[0]
>```

this change is compatible with both Python3 (`3.7.3`) and Python2 (`2.7.16`).  tested on the following host:

```
Operating System: Raspbian GNU/Linux 10 (buster)
Kernel: Linux 5.10.63-v7+
Architecture: arm
```

waiting until the end of the week for @Kyuchumimo to submit a PR to the [`the-raspberry-pi-guy:master`](https://github.com/the-raspberry-pi-guy/lcd) branch.  otherwise, I'll submit one on my own, credit him in the commit message, and close this issue (#33) upon merge.  please let me know about any objections until then.
