### ISSUE TITLE
Display IP adress

### ISSUE THREAD

**Issue by Mikes-Git** [the-raspberry-pi-guy/lcd#59]
@Sierra007117 Displaying the IP Address shows following:

b'[IP Address]'

how can I get the b and the '' not to be displayed?

Is there a way to display the port as well?

**Comment by cgomesu** [comment]
user ignored the issue template.

**Comment by Mikes-Git** [comment]
Help out a noop, what did I do wrong?

**Comment by Sierra007117** [comment]
The 'b' prefix in front of the IP address indicates that it is a bytes object, rather than a string. To remove the prefix and the quotes, you can use the decode() method to convert the bytes object to a string. 

As for the port, between the protocols User Datagram Protocol (UDP) and Transmission Control Protocol (TCP), there are 65,535 ports available for communication between devices. If you meant the port used for SSH, you could modify the check_output command to run the sshd command with the -T flag, which displays the port number used for SSH.
